In [8]:
import pandas as pd
import numpy as np
import re
from collections import Counter
from pymorphy3 import MorphAnalyzer

morph = MorphAnalyzer()

In [5]:
df = pd.read_csv('2_func_markers.csv', sep=',')
del df['district_norm']
df.head(10)

,number,name_object,district,date_buckets_2,func_markers
0,1,Здание Консисторского управления Могилевской Р...,Адмиралтейский,1850-1899,NaN
1,2,Здание манежа (экзерциргауса) лейб-гвардии Изм...,Адмиралтейский,1750-1799,NaN
2,3,"Дом, где в начале 1895 г. Ленин В.И. встречалс...",Адмиралтейский,NaN,NaN
3,4,Трансформаторная подстанция,Адмиралтейский,1900-1949,NaN
4,5,Дом А.Н. Васильева,Адмиралтейский,1900-1949,NaN
5,6,Манеж графа Г.И. Рибопьера (Здание Санкт-Петер...,Адмиралтейский,1850-1899,общество
6,7,Особняк и доходный дом Н.Г. Кудрявцева,Адмиралтейский,1850-1899,"особняк,доходный"
7,8,Дом Закуриной,Адмиралтейский,1850-1899,NaN
8,9,Дом З.Н. Левина,Адмиралтейский,1850-1899,NaN
9,10,Дом Е.Е. Глухарева,Адмиралтейский,1900-1949,NaN

In [10]:
func_list = [
    'могила',
    'жилой',
    'сад',
    'ограда',
    'мост',
    'статуя',
    'особняк',
    'церковь',
    'дача',
    'завод',
    'парк',
    'ворота',
    'бюст',
    'доходный',
    'фонтан'
]

In [16]:
marks = []
districts = []

for distr, mark, name in zip(df['district'], df['func_markers'], df['name_object']):
    for w in name.split(' '):
        if len(w) > 2:
            w = morph.parse(w)[0].normal_form
            if w in func_list:
                districts.append(distr)
                marks.append(w)

data = {
    'district': districts,
    'func_markers': marks
}

df_d_m = pd.DataFrame(data)
df_d_m.head()

         district func_markers
0  Адмиралтейский      особняк
1  Адмиралтейский     доходный
2  Адмиралтейский          сад
3  Адмиралтейский       ограда
4  Адмиралтейский       ограда

In [17]:
df_d_m.to_csv('markers_to_districts.csv', index=False, encoding='utf-8-sig')